server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todo_db
    username: todo_user
    password: todo_pass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

app:
  jwt:
    secret: "CHANGE_THIS_TO_A_LONG_RANDOM_SECRET_32+_CHARS"
    expirationMinutes: 60
